version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: ulohaTrixi-postgres
    environment:
      POSTGRES_DB: ulohaTrixi_db
      POSTGRES_USER: ulohaTrixi_user
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: