spring.application.name=ulohaTrixi

# Připojení k PostgreSQL v Dockeru
spring.datasource.url=jdbc:postgresql://localhost:5433/ulohaTrixi_db
spring.datasource.username=ulohaTrixi_user
spring.datasource.password=${DB_HESLO}
spring.datasource.driver-class-name=org.postgresql.Driver

# Nastavení Hibernate (JPA)
# update = automaticky vytvoří nebo upraví tabulky v databázi podle vašich Java tříd (@Entity)
spring.jpa.hibernate.ddl-auto=update

# Zobrazování SQL dotazů v konzoli (užitečné při ladění a testování)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
